version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.486.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.557.0
    - 1.563.0
    - 1.564.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
    - 7.13.15
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.18
    - 0.21.19
  - dependency-name: bl
    versions:
    - 4.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: pug
    versions:
    - 3.0.1
  - dependency-name: currency-symbol-map
    versions:
    - 5.0.1
  - dependency-name: i18next
    versions:
    - 19.8.6
    - 19.8.7
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
