dist: bionic
language: node_js
node_js:
  - 'stable'
install: npm install
before_script:
  - cp config.sample.js config.js
script: npm test
cache:
  directories:
    - node_modules
notifications:
  irc: "chat.freenode.net#mrnodebot"
